### ISSUE TITLE
License allows for selling and/or (re)distributing the Homebrew Channel, regardless of anything.

### ISSUE THREAD

**Issue by alfredocisneros** [fail0verflow/hbc#21]
I have been researching this, and noticed something quite important that'll definitely need for quite a bit of time for changes in the HackMii Installer and the Homebrew Channel. The Homebrew Channel's source code is licensed under the GNU General Public License, version 2. This license allows for selling and redistributing the software. In fact, even GNU, the makers of the General Public License, encourage selling free software (http://www.gnu.org/philosophy/selling.html). 

For clarification, I am not someone who redistributes or sells the HackMii installer, however, this is something that no one has brought up, and I would like to bring it up, as the issue is that the creators of the Homebrew Channel are misleading people who are going to hack their Wii consoles into thinking that the Homebrew Channel isn't able to be redistributed or sold.

**Comment by Masamune3210** [comment]
Given the dangers that a even slightly malfunctioning HackMii installer can pose to someone's Wii, I understand the want for clarification but malicious people rarely care what the license is anyway. If people are going to try to sell the installer, they are going to try whether they are told they can or not

**Comment by marcan** [comment]
The code in this repo is licensed under the GPLv2, and you are free to sell it as long as you abide by the terms of the license. The official installer binaries are not, and you are not allowed to sell them or any portion thereof. There is no inconsistency here. The installer isn't even part of this repo.

**Comment by alfredocisneros** [comment]
Okay, thanks for the information, I was just confused,
