### ISSUE TITLE
Homebrew Channel WebOS Error

### ISSUE THREAD

**Issue by Alpha-Centaurus** [fail0verflow/hbc#22]
Hello.
I have installed Homebrew Channel to my WebOS LG TV. But I cannot install any application from there. It always breaks with an error message.
The message is:
**An error occured during installation: Unable to exec luna-send-pub: Error: Failed to call getIDs**
I have no root access, but I learned that it isn't required.
The Homebrew Channel was installed from webosapp.club/online. Version 0.4.0
I can see that the latest one is 0.5.0 but it isn't there.
And I cannot update it from Homebrew Channel too - the error is the same.
What can I do? Thank you.

**Comment by shuffle2** [comment]
you have the wrong github project
