### ISSUE TITLE
Question about the bubbles minigame removed in 1.0.5

### ISSUE THREAD

**Issue by korbough** [fail0verflow/hbc#27]
Would any of you happen to still have the minigame's code? The minigame in question is the one where you hid the UI and popped bubbles, at which point a score would appear, which increases with every bubble pop.

**Comment by dhewg** [comment]
This? It's been a while, so a revert probably won't apply as-is anymore ;)
[0001-removed-that-silly-bubble-game.patch.txt](https://github.com/fail0verflow/hbc/files/13826624/0001-removed-that-silly-bubble-game.patch.txt)

**Comment by korbough** [comment]
Thanks a lot! i had a feeling it wouldn't just apply, but I bet it could be finagled in somehow.
