### ISSUE TITLE
[QUESTION] Can you put a precompiled wad in the releases section of this repo?

### ISSUE THREAD

**Issue by infinity5** [fail0verflow/hbc#6]
People who are not good with compiling (I'm not) might have trouble compiling the wad. It would be helpful to many people if you put a wad in the releases.

**Comment by DoctorTiti** [comment]
or just give some sources to help to compile it ;) but i'm not an expert, and i don't know how to do this, but i'm sure, then if you google-it, you can find some people who made a tutorial to do this

**Comment by Jasjar42** [comment]
I managed to find a copy that someone compiled: https://gbatemp.net/threads/v-wii-homebrew-channel-open-sourced.450288/page-4#post-6871034

**Comment by marcan** [comment]
We're deliberately not providing binaries, as this release is not tested to our usual standards.
