### ISSUE TITLE
[NOT SPECIFICALLY RELATED TO THE CODE] BootMii Issue

### ISSUE THREAD

**Issue by PokeAcer** [fail0verflow/hbc#7]
BootMii needs an update of sorts to check for OHBC: I prefer it because it doesnt do the update.sxml check and thus doesnt clutter my dumps with 404s, but I can't use it because it doesn't load from BootMii.

**Comment by marcan** [comment]
Off-topic. Sorry, no new BootMii updates are planned at this time.

**Comment by PokeAcer** [comment]
Understandable, thank you.
